[package]
name = "rust-example"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.12.5", features = ["json"] }

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
anyhow = "1.0.86"
